### ISSUE TITLE
不好使啊，运行你的项目都失败

### ISSUE THREAD

**Issue by zhanmy** [nigulasikk/freeStylePlugin#1]
Segment need nodejieba, please run '$ npm install nodejieba'.
 分词需要使用 nodejieba 模块，请运行 '$ npm install nodejieba' 并确保安装完成

文档里没说明啊

**Comment by nigulasikk** [comment]
我这个项目不是依赖pinyin 库吗，pinyin库依赖nodejieba模块的。所以你执行 npm install 的时候 ，都会自动安装上的呀，不需要额外运行的。   
请问你的node 版本是多少？要不更新到最新的，再试一下

**Comment by nigulasikk** [comment]
@zhanmy 我这个项目不是依赖pinyin 库吗，pinyin库依赖nodejieba模块的。所以你执行 npm install 的时候 ，都会自动安装上的呀，不需要额外运行的。
请问你的node 版本是多少？要不更新到最新的，再试一下

**Comment by zhanmy** [comment]
node版本8.2.1  不好使啊，我更新下试一试

**Comment by nigulasikk** [comment]
@zhanmy  nodeV8.2.1 是没问题的， 问题应该处在npm install 的时候 。安装依赖nodejieba的时候是否有报错或警告？

**Comment by zhanmy** [comment]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT                                   HON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\99592\AppData\Roaming\                                   npm\node_modules\cnpm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\99592\AppData\Roaming\n                                   pm\node_modules\cnpm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\99592\AppData\Roaming\npm\node_modules\cnpm\node_                                   modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\99592\\AppDat                                   a\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\nod                                   e-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\99592\Desktop\freeStylePlugin-master\node_modules\_nodejie                                   ba@2.2.5@nodejieba
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
[nodejieba@^2.2.1] optional install error: Error: Run "C:\Windows\system32\cmd.e                                   xe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\99592\AppData\Roaming\npm\node_module                                   s\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)







确实有报错 求解答

**Comment by nigulasikk** [comment]
@zhanmy  第二行log 要求你本地要有 python 环境

**Comment by zhanmy** [comment]
也就是说这个项目需要python 环境么， 文档里没有介绍啊

**Comment by zhanmy** [comment]
安装了python 环境以及配置了环境变量，依旧不好用

**Comment by zhanmy** [comment]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe                                                                                                                                                                                               ` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\99592\AppData\Roaming\npm\no                                                                                                                                                                                               de_modules\cnpm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                                                                                                               s.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\99592\\AppDat                                                                                                                                                                                               a\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\\nod                                                                                                                                                                                               e-gyp.js" "rebuild"
gyp ERR! cwd D:\Work\PersonalProject\zAdmin-node\node_modules\_nodejieba@2.2.5@n                                                                                                                                                                                               odejieba
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
[nodejieba@^2.2.1] optional install error: Error: Run "C:\Windows\system32\cmd.e                                                                                                                                                                                               xe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\99592\AppData\Roaming\npm\node_module                                                                                                                                                                                               s\cnpm\node_modules\runscript\index.js:74:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by nigulasikk** [comment]
@zhanmy  恩 ，你这边这下python环境好了。现在问题出在 node-gyp（nodejieba依赖的） 模块的运行，应该是windows环境下执行这个模块出现的问题。所以试着在 https://github.com/nodejs/node-gyp  这边找找答案。试着搜下这个

> gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1

 其实我个人也想尽量把项目做得简单，所以整个项目只依赖了一个pinyin库，但殊不知每一个这种库都会依赖于一些库（都是站在巨人的肩膀上写出来的），每个库在不同开发环境下表现又不一样☹【哭脸】，遇到这种问题稍微要点耐心哈~

**Comment by zhanmy** [comment]
非常感谢，我看了你的算法 受益匪浅 我自己谢了个web版的 纯前端实现 
 
------------------ Original ------------------
From: "kaikai"; 
Date: 2017年12月12日(星期二) 下午5:46
To: "nigulasikk/freeStylePlugin"; 
Cc: "zhanmy"; "Mention"; 
Subject: Re: [nigulasikk/freeStylePlugin] 不好使啊，运行你的项目都失败 (#1)

 

@zhanmy  恩 ，你这边这下python环境好了。现在问题出在 node-gyp（nodejieba依赖的） 模块的运行，应该是windows环境下执行这个模块出现的问题。所以试着在 https://github.com/nodejs/node-gyp  这边找找答案。试着搜下这个
  
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
  
其实我个人也想尽量把项目做得简单，所以整个项目只依赖了一个pinyin库，但殊不知每一个这种库都会依赖于一些库（都是站在巨人的肩膀上写出来的），每个库在不同开发环境下表现又不一样【哭脸】，遇到这种问题稍微要点耐心哈~
